In [14]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv(r"C:\Users\jhenk\Downloads\loan_data.csv")

# Show first rows
df.head()

,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid
0,1,debt_consolidation,0.1189,829.10,11.350407,19.48,737,5639.958333,28854,52.1,0,0,0,0
1,1,credit_card,0.1071,228.22,11.082143,14.29,707,2760.000000,33623,76.7,0,0,0,0
2,1,debt_consolidation,0.1357,366.86,10.373491,11.63,682,4710.000000,3511,25.6,1,0,0,0
3,1,debt_consolidation,0.1008,162.34,11.350407,8.10,712,2699.958333,33667,73.2,1,0,0,0
4,1,credit_card,0.1426,102.92,11.299732,14.97,667,4066.000000,4740,39.5,0,1,0,0

In [16]:
# Dataset shape
print("Dataset Shape:", df.shape)

# Column names
print("\nColumns:")
print(df.columns)

# Dataset information
df.info()

Dataset Shape: (9578, 14)

Columns:
Index(['credit.policy', 'purpose', 'int.rate', 'installment', 'log.annual.inc',
       'dti', 'fico', 'days.with.cr.line', 'revol.bal', 'revol.util',
       'inq.last.6mths', 'delinq.2yrs', 'pub.rec', 'not.fully.paid'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9578 entries, 0 to 9577
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   credit.policy      9578 non-null   int64
 1   purpose            9578 non-null   object
 2   int.rate           9578 non-null   float64
 3   installment        9578 non-null   float64
 4   log.annual.inc     9578 non-null   float64
 5   dti                9578 non-null   float64
 6   fico               9578 non-null   int64
 7   days.with.cr.line  9578 non-null   float64
 8   revol.bal          9578 non-null   int64
 9   revol.util         9578 non-null   float64
 10  inq.last.6mths     9578 non-null   int64
 11  delinq.2yrs        9578 non-null   int64
 12  pub.rec            9578 non-null   int64
 13  not.fully.paid     9578 non-null   int64
dtypes: float64(6), int64(7), object(1)
memory usage: 1.0+ MB

In [17]:
df.isnull().sum()

credit.policy        0
purpose              0
int.rate             0
installment          0
log.annual.inc       0
dti                  0
fico                 0
days.with.cr.line    0
revol.bal            0
revol.util           0
inq.last.6mths       0
delinq.2yrs          0
pub.rec              0
not.fully.paid       0
dtype: int64

In [18]:
# Convert categorical column into numerical columns
df = pd.get_dummies(df, columns=['purpose'], drop_first=True)

# Show first rows
df.head()

,credit.policy,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,purpose_credit_card,purpose_debt_consolidation,purpose_educational,purpose_home_improvement,purpose_major_purchase,purpose_small_business
0,1,0.1189,829.10,11.350407,19.48,737,5639.958333,28854,52.1,0,0,0,0,False,True,False,False,False,False
1,1,0.1071,228.22,11.082143,14.29,707,2760.000000,33623,76.7,0,0,0,0,True,False,False,False,False,False
2,1,0.1357,366.86,10.373491,11.63,682,4710.000000,3511,25.6,1,0,0,0,False,True,False,False,False,False
3,1,0.1008,162.34,11.350407,8.10,712,2699.958333,33667,73.2,1,0,0,0,False,True,False,False,False,False
4,1,0.1426,102.92,11.299732,14.97,667,4066.000000,4740,39.5,0,1,0,0,True,False,False,False,False,False

In [19]:
print("New Dataset Shape:", df.shape)

New Dataset Shape: (9578, 19)

In [20]:
len(df)

9578

In [21]:
X = df.drop("not.fully.paid", axis=1)
y = df["not.fully.paid"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (9578, 18)
y shape: (9578,)

In [22]:
#Train Test Split 

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training set:", X_train.shape)
print("Testing set:", X_test.shape)

Training set: (7662, 18)
Testing set: (1916, 18)

In [23]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [24]:
# Model Training (Logistic Regression) 

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000)

In [25]:
y_pred = model.predict(X_test_scaled)

In [26]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Accuracy: 0.8397703549060542

Classification Report:

              precision    recall  f1-score   support

           0       0.84      0.99      0.91      1611
           1       0.45      0.03      0.06       305

    accuracy                           0.84      1916
   macro avg       0.65      0.51      0.48      1916
weighted avg       0.78      0.84      0.78      1916

In [27]:
# Working to Solve Class Imbalance
y.value_counts()

not.fully.paid
0    8045
1    1533
Name: count, dtype: int64

In [28]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(X_train_scaled, y_train)

In [29]:
print("Before SMOTE:")
print(y_train.value_counts())

print("\nAfter SMOTE:")
print(pd.Series(y_train_smote).value_counts())

Before SMOTE:
not.fully.paid
0    6434
1    1228
Name: count, dtype: int64

After SMOTE:
not.fully.paid
0    6434
1    6434
Name: count, dtype: int64

In [30]:
model = LogisticRegression(max_iter=1000)

model.fit(X_train_smote, y_train_smote)

LogisticRegression(max_iter=1000)

In [31]:
y_pred = model.predict(X_test_scaled)

In [32]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Accuracy: 0.6346555323590815

Classification Report:

              precision    recall  f1-score   support

           0       0.91      0.63      0.74      1611
           1       0.26      0.68      0.37       305

    accuracy                           0.63      1916
   macro avg       0.58      0.65      0.56      1916
weighted avg       0.81      0.63      0.68      1916

In [ ]:
# HyperParameter Tuning using GridSearchCV

In [33]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

# Parameter grid
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'solver': ['liblinear', 'lbfgs']
}

log_model = LogisticRegression(max_iter=1000)

grid = GridSearchCV(log_model, param_grid, cv=5, scoring='f1', n_jobs=-1)

grid.fit(X_train_smote, y_train_smote)

GridSearchCV(cv=5, estimator=LogisticRegression(max_iter=1000), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10, 100],
                         'solver': ['liblinear', 'lbfgs']},
             scoring='f1')

In [34]:
print("Best Parameters:", grid.best_params_)

Best Parameters: {'C': 0.01, 'solver': 'liblinear'}

In [35]:
best_model = grid.best_estimator_

y_pred = best_model.predict(X_test_scaled)

In [36]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Accuracy: 0.6367432150313153

Classification Report:

              precision    recall  f1-score   support

           0       0.91      0.63      0.74      1611
           1       0.26      0.68      0.37       305

    accuracy                           0.64      1916
   macro avg       0.59      0.66      0.56      1916
weighted avg       0.81      0.64      0.69      1916

In [ ]:
# Model Training (Random Forest)

In [37]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf_model.fit(X_train_smote, y_train_smote)

RandomForestClassifier(n_estimators=200, random_state=42)

In [38]:
rf_pred = rf_model.predict(X_test_scaled)

In [39]:
print("Random Forest Accuracy:", accuracy_score(y_test, rf_pred))

print("\nRandom Forest Classification Report:\n")
print(classification_report(y_test, rf_pred))

Random Forest Accuracy: 0.8115866388308977

Random Forest Classification Report:

              precision    recall  f1-score   support

           0       0.86      0.93      0.89      1611
           1       0.33      0.18      0.23       305

    accuracy                           0.81      1916
   macro avg       0.59      0.55      0.56      1916
weighted avg       0.77      0.81      0.79      1916

In [40]:
# Comparing Logistic Regression and Random Forest

In [41]:
import pandas as pd

models = ['Logistic Regression', 'Random Forest']
accuracy = [
    accuracy_score(y_test, y_pred),
    accuracy_score(y_test, rf_pred)
]

comparison = pd.DataFrame({
    'Model': models,
    'Accuracy': accuracy
})

comparison

                 Model  Accuracy
0  Logistic Regression  0.636743
1        Random Forest  0.811587

In [ ]:
# Model Training (XGBoost)

In [42]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\jhenk\onedrive\desktop\projects\credit card approval project\venv\lib\site-packages (from xgboost) (2.4.2)
Requirement already satisfied: scipy in c:\users\jhenk\onedrive\desktop\projects\credit card approval project\venv\lib\site-packages (from xgboost) (1.17.1)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB 991.0 kB/s eta 0:01:43
   ---------------------------------------- 0.1/101.7 MB 1.7 MB/s eta 0:01:00
   ---------------------------------------- 0.3/101.7 MB 2.1 MB/s eta 0:00:48
   ---------------------------------------- 0.6/101.7 MB 3.1 MB/s eta 0:00:33
   ---------------------------------------- 0.9/101.7 MB 3.7 MB/s eta 0:00:28
   ---------------------------------------- 1.2/101.7 MB 4.4 MB/s eta 0:00:24
    --------------------------------------- 1.6/101.7 MB 5.3 MB/s eta 0:00:20
    --------------------------------------- 1.9/101.7 MB 5.3 MB/s eta 0:00:19
    --------------------------------------- 2.3/101.7 MB 5.6 MB/s eta 0:00:18
   - -------------------------------------- 2.7/101.7 MB 5.9 MB/s eta 0:00:17
   - -------------------------------------- 3.1/101.7 MB 6.2 MB/s eta 0:00:16
   - -------------------------------------- 3.6/101.7 MB 6.5 MB/s eta 0:00:16
   - -------------------------------------- 4.0/101.7 MB 6.8 MB/s eta 0:00:15
   - -------------------------------------- 4.6/101.7 MB 7.1 MB/s eta 0:00:14
   - -------------------------------------- 5.0/101.7 MB 7.3 MB/s eta 0:00:14
   -- ------------------------------------- 5.3/101.7 MB 7.2 MB/s eta 0:00:14
   -- ------------------------------------- 5.7/101.7 MB 7.4 MB/s eta 0:00:13
   -- ------------------------------------- 6.1/101.7 MB 7.2 MB/s eta 0:00:14
   -- ------------------------------------- 6.4/101.7 MB 7.2 MB/s eta 0:00:14
   -- ------------------------------------- 6.8/101.7 MB 7.3 MB/s eta 0:00:14
   -- ------------------------------------- 7.2/101.7 MB 7.3 MB/s eta 0:00:13
   --- ------------------------------------ 7.6/101.7 MB 7.4 MB/s eta 0:00:13
   --- ------------------------------------ 8.2/101.7 MB 7.6 MB/s eta 0:00:13
   --- ------------------------------------ 8.7/101.7 MB 7.7 MB/s eta 0:00:13
   --- ------------------------------------ 9.1/101.7 MB 7.8 MB/s eta 0:00:12
   --- ------------------------------------ 9.7/101.7 MB 8.0 MB/s eta 0:00:12
   --- ------------------------------------ 10.1/101.7 MB 7.9 MB/s eta 0:00:12
   ---- ----------------------------------- 10.2/101.7 MB 7.9 MB/s eta 0:00:12
   ---- ----------------------------------- 10.4/101.7 MB 8.0 MB/s eta 0:00:12
   ---- ----------------------------------- 10.8/101.7 MB 8.4 MB/s eta 0:00:11
   ---- ----------------------------------- 11.0/101.7 MB 8.2 MB/s eta 0:00:12
   ---- ----------------------------------- 11.0/101.7 MB 8.0 MB/s eta 0:00:12
   ---- ----------------------------------- 11.4/101.7 MB 8.0 MB/s eta 0:00:12
   ---- ----------------------------------- 11.6/101.7 MB 7.9 MB/s eta 0:00:12
   ---- ----------------------------------- 12.0/101.7 MB 7.9 MB/s eta 0:00:12
   ---- ----------------------------------- 12.5/101.7 MB 7.9 MB/s eta 0:00:12
   ----- ---------------------------------- 12.8/101.7 MB 7.9 MB/s eta 0:00:12
   ----- ---------------------------------- 13.3/101.7 MB 7.9 MB/s eta 0:00:12
   ----- ---------------------------------- 13.4/101.7 MB 7.8 MB/s eta 0:00:12
   ----- ---------------------------------- 13.4/101.7 MB 7.8 MB/s eta 0:00:12
   ----- ---------------------------------- 13.4/101.7 MB 7.4 MB/s eta 0:00:12
   ----- ---------------------------------- 13.4/101.7 MB 7.4 MB/s eta 0:00:12
   ----- ---------------------------------- 13.5/101.7 MB 6.8 MB/s eta 0:00:13
   ----- ---------------------------------- 13.8/101.7 MB 6.8 MB/s eta 0:00:13
   ----- ---------------------------------- 14.0/101.7 MB 6.7 MB/s eta 0:00:14
   ----- ---------------------------------- 14.2/101.7 MB 6.6 MB/s eta 0:00:14
   ----- ---------------------------------- 14.2/101.7 MB 6.4 MB/s eta 0:00:14
   ----- ---------------------------------- 14.2/101.7 MB 6.4 MB/s eta 0:00:14
   ----- ---------------------------------- 14.4/101.7 MB 6.0 MB/s eta 0:00:15
   ----- ---------------------------------- 14.7/101.7 MB 6.0 MB/s eta 0:00:15
   ----- ---------------------------------- 14.8/101.7 MB 5.9 MB/s eta 0:00:15
   ----- ---------------------------------- 14.8/101.7 MB 5.8 MB/s eta 0:00:15
   ----- ---------------------------------- 14.8/101.7 MB 5.8 MB/s eta 0:00:15
   ----- ---------------------------------- 14.9/101.7 MB 5.5 MB/s eta 0:00:16
   ----- ---------------------------------- 15.0/101.7 MB 5.3 MB/s eta 0:00:17
   ------ --------------------------------- 15.3/101.7 MB 5.3 MB/s eta 0:00:17
   ------ --------------------------------- 15.6/101.7 MB 5.4 MB/s eta 0:00:17
   ------ --------------------------------- 15.8/101.7 MB 5.2 MB/s eta 0:00:17
   ------ --------------------------------- 16.0/101.7 MB 5.2 MB/s eta 0:00:17
   ------ --------------------------------- 16.2/101.7 MB 5.1 MB/s eta 0:00:17
   ------ --------------------------------- 16.3/101.7 MB 5.0 MB/s eta 0:00:17
   ------ --------------------------------- 16.3/101.7 MB 5.0 MB/s eta 0:00:18
   ------ --------------------------------- 16.7/101.7 MB 4.9 MB/s eta 0:00:18
   ------ --------------------------------- 16.7/101.7 MB 4.9 MB/s eta 0:00:18
   ------ --------------------------------- 16.7/101.7 MB 4.9 MB/s eta 0:00:18
   ------ --------------------------------- 16.9/101.7 MB 4.6 MB/s eta 0:00:19
   ------ --------------------------------- 17.3/101.7 MB 4.6 MB/s eta 0:00:19
   ------ --------------------------------- 17.4/101.7 MB 4.6 MB/s eta 0:00:19
   ------- -------------------------------- 17.8/101.7 MB 4.5 MB/s eta 0:00:19
   ------- -------------------------------- 18.1/101.7 MB 4.5 MB/s eta 0:00:19
   ------- -------------------------------- 18.4/101.7 MB 4.5 MB/s eta 0:00:19
   ------- -------------------------------- 18.5/101.7 MB 4.4 MB/s eta 0:00:19
   ------- -------------------------------- 18.6/101.7 MB 4.3 MB/s eta 0:00:20
   ------- -------------------------------- 18.6/101.7 MB 4.3 MB/s eta 0:00:20
   ------- -------------------------------- 18.7/101.7 MB 4.2 MB/s eta 0:00:20
   ------- -------------------------------- 18.8/101.7 MB 4.1 MB/s eta 0:00:21
   ------- -------------------------------- 18.9/101.7 MB 4.1 MB/s eta 0:00:21
   ------- -------------------------------- 19.2/101.7 MB 4.0 MB/s eta 0:00:21
   ------- -------------------------------- 19.5/101.7 MB 4.0 MB/s eta 0:00:21
   ------- -------------------------------- 19.5/101.7 MB 3.9 MB/s eta 0:00:21
   ------- -------------------------------- 19.6/101.7 MB 3.9 MB/s eta 0:00:22
   ------- -------------------------------- 19.9/101.7 MB 3.8 MB/s eta 0:00:22
   ------- -------------------------------- 20.3/101.7 MB 3.8 MB/s eta 0:00:22
   -------- ------------------------------- 20.5/101.7 MB 3.9 MB/s eta 0:00:21
   -------- ------------------------------- 20.8/101.7 MB 3.9 MB/s eta 0:00:21
   -------- ------------------------------- 21.0/101.7 MB 3.8 MB/s eta 0:00:22
   -------- ------------------------------- 21.4/101.7 MB 4.0 MB/s eta 0:00:21
   -------- ------------------------------- 21.9/101.7 MB 4.0 MB/s eta 0:00:21
   -------- ------------------------------- 22.1/101.7 MB 3.9 MB/s eta 0:00:21
   -------- ------------------------------- 22.2/101.7 MB 3.9 MB/s eta 0:00:21
   -------- ------------------------------- 22.4/101.7 MB 3.9 MB/s eta 0:00:21
   -------- ------------------------------- 22.5/101.7 MB 3.8 MB/s eta 0:00:21
   -------- ------------------------------- 22.9/101.7 MB 3.8 MB/s eta 0:00:21
   --------- ------------------------------ 23.0/101.7 MB 3.8 MB/s eta 0:00:21
   --------- ------------------------------ 23.1/101.7 MB 3.7 MB/s eta 0:00:22
   --------- ------------------------------ 23.5/101.7 MB 3.7 MB/s eta 0:00:22
   --------- ------------------------------ 23.7/101.7 MB 4.0 MB/s eta 0:00:20
   --------- ------------------------------ 24.0/101.7 MB 4.0 MB/s eta 0:00:20
   --------- ------------------------------ 24.6/101.7 MB 4.3 MB/s eta 0:00:19
   --------- ------------------------------ 25.0/101.7 MB 4.4 MB/s eta 0:00:18
   --------- ------------------------------ 25.3/101.7 MB 4.7 MB/s eta 0:00:17
   ---------- ----------------------------- 25.8/101.7 MB 4.7 MB/s eta 0:00:17
   ---------- ----------------------------- 25.9/101.7 MB 4.6 MB/s eta 0:00:17
   ---------- ----------------------------- 26.2/101.7 MB 4.7 MB/s eta 0:00:17
   ---------- ----------------------------- 26.2/101.7 MB 4.7 MB/s eta 0:00:17
   ---------- ----------------------------- 26.9/101.7 MB 4.9 MB/s eta 0:00:16
   ---------- ----------------------------- 27.2/101.7 MB 5.2 MB/s eta 0:00:15
   ---------- ----------------------------- 27.5/101.7 MB 5.2 MB/s eta 0:00:15
   ---------- ----------------------------- 27.7/101.7 MB 5.2 MB/s eta 0:00:15
   ----------- ---------------------------- 28.1/101.7 MB 5.2 MB/s eta 0:00:15
   ----------- ---------------------------- 28.1/101.7 MB 5.2 MB/s eta 0:00:15
   ----------- ---------------------------- 28.4/101.7 MB 5.2 MB/s eta 0:00:15
   ----------- ---------------------------- 28.6/101.7 MB 5.1 MB/s eta 0:00:15
   ----------- ---------------------------- 29.0/101.7 MB 5.6 MB/s eta 0:00:14
   ----------- ---------------------------- 29.3/101.7 MB 5.6 MB/s eta 0:00:13
   ----------- ---------------------------- 29.3/101.7 MB 5.7 MB/s eta 0:00:13
   ----------- ---------------------------- 29.5/101.7 MB 5.5 MB/s eta 0:00:14
   ----------- ---------------------------- 29.8/101.7 MB 5.7 MB/s eta 0:00:13
   ----------- ---------------------------- 30.0/101.7 MB 5.7 MB/s eta 0:00:13
   ----------- ---------------------------- 30.2/101.7 MB 5.7 MB/s eta 0:00:13
   ----------- ---------------------------- 30.3/101.7 MB 5.6 MB/s eta 0:00:13
   ------------ --------------------------- 30.6/101.7 MB 5.6 MB/s eta 0:00:13
   ------------ --------------------------- 30.9/101.7 MB 5.6 MB/s eta 0:00:13
   ------------ --------------------------- 31.2/101.7 MB 5.6 MB/s eta 0:00:13
   ------------ --------------------------- 31.5/101.7 MB 5.5 MB/s eta 0:00:13
   ------------ --------------------------- 31.7/101.7 MB 5.6 MB/s eta 0:00:13
   ------------ --------------------------- 31.9/101.7 MB 5.5 MB/s eta 0:00:13
   ------------ --------------------------- 32.2/101.7 MB 5.4 MB/s eta 0:00:13
   ------------ --------------------------- 32.6/101.7 MB 5.5 MB/s eta 0:00:13
   ------------ --------------------------- 32.8/101.7 MB 5.7 MB/s eta 0:00:13
   ------------- -------------------------- 33.3/101.7 MB 5.8 MB/s eta 0:00:12
   ------------- -------------------------- 33.6/101.7 MB 5.9 MB/s eta 0:00:12
   ------------- -------------------------- 33.8/101.7 MB 5.9 MB/s eta 0:00:12
   ------------- -------------------------- 34.1/101.7 MB 5.8 MB/s eta 0:00:12
   ------------- -------------------------- 34.5/101.7 MB 5.8 MB/s eta 0:00:12
   ------------- -------------------------- 34.8/101.7 MB 5.8 MB/s eta 0:00:12
   ------------- -------------------------- 35.0/101.7 MB 5.8 MB/s eta 0:00:12
   ------------- -------------------------- 35.3/101.7 MB 5.7 MB/s eta 0:00:12
   ------------- -------------------------- 35.5/101.7 MB 5.6 MB/s eta 0:00:12
   -------------- ------------------------- 35.7/101.7 MB 5.6 MB/s eta 0:00:12
   -------------- ------------------------- 36.0/101.7 MB 5.5 MB/s eta 0:00:12
   -------------- ------------------------- 36.2/101.7 MB 5.6 MB/s eta 0:00:12
   -------------- ------------------------- 36.3/101.7 MB 5.5 MB/s eta 0:00:12
   -------------- ------------------------- 36.5/101.7 MB 5.6 MB/s eta 0:00:12
   -------------- ------------------------- 36.7/101.7 MB 5.5 MB/s eta 0:00:12
   -------------- ------------------------- 36.9/101.7 MB 5.4 MB/s eta 0:00:13
   -------------- ------------------------- 37.1/101.7 MB 5.3 MB/s eta 0:00:13
   -------------- ------------------------- 37.4/101.7 MB 5.3 MB/s eta 0:00:13
   -------------- ------------------------- 37.5/101.7 MB 5.2 MB/s eta 0:00:13
   -------------- ------------------------- 37.7/101.7 MB 5.2 MB/s eta 0:00:13
   -------------- ------------------------- 38.0/101.7 MB 5.2 MB/s eta 0:00:13
   --------------- ------------------------ 38.5/101.7 MB 5.4 MB/s eta 0:00:12
   --------------- ------------------------ 38.6/101.7 MB 5.3 MB/s eta 0:00:12
   --------------- ------------------------ 39.2/101.7 MB 5.5 MB/s eta 0:00:12
   --------------- ------------------------ 39.4/101.7 MB 5.4 MB/s eta 0:00:12
   --------------- ------------------------ 39.6/101.7 MB 5.3 MB/s eta 0:00:12
   --------------- ------------------------ 39.6/101.7 MB 5.3 MB/s eta 0:00:12
   --------------- ------------------------ 39.6/101.7 MB 5.3 MB/s eta 0:00:12
   --------------- ------------------------ 39.6/101.7 MB 5.3 MB/s eta 0:00:12
   --------------- ------------------------ 39.6/101.7 MB 5.1 MB/s eta 0:00:13
   --------------- ------------------------ 39.6/101.7 MB 4.9 MB/s eta 0:00:13
   --------------- ------------------------ 39.6/101.7 MB 4.9 MB/s eta 0:00:13
   --------------- ------------------------ 39.6/101.7 MB 4.7 MB/s eta 0:00:14
   --------------- ------------------------ 39.7/101.7 MB 4.6 MB/s eta 0:00:14
   --------------- ------------------------ 39.8/101.7 MB 4.5 MB/s eta 0:00:14
   --------------- ------------------------ 39.9/101.7 MB 4.5 MB/s eta 0:00:14
   --------------- ------------------------ 39.9/101.7 MB 4.4 MB/s eta 0:00:15
   --------------- ------------------------ 40.0/101.7 MB 4.4 MB/s eta 0:00:15
   --------------- ------------------------ 40.2/101.7 MB 4.3 MB/s eta 0:00:15
   --------------- ------------------------ 40.4/101.7 MB 4.4 MB/s eta 0:00:14
   --------------- ------------------------ 40.6/101.7 MB 4.4 MB/s eta 0:00:14
   ---------------- ----------------------- 40.7/101.7 MB 4.3 MB/s eta 0:00:15
   ---------------- ----------------------- 41.1/101.7 MB 4.3 MB/s eta 0:00:14
   ---------------- ----------------------- 41.2/101.7 MB 4.3 MB/s eta 0:00:15
   ---------------- ----------------------- 41.3/101.7 MB 4.2 MB/s eta 0:00:15
   ---------------- ----------------------- 41.4/101.7 MB 4.1 MB/s eta 0:00:15
   ---------------- ----------------------- 41.4/101.7 MB 4.1 MB/s eta 0:00:15
   ---------------- ----------------------- 41.4/101.7 MB 4.0 MB/s eta 0:00:16
   ---------------- ----------------------- 41.4/101.7 MB 3.9 MB/s eta 0:00:16
   ---------------- ----------------------- 41.5/101.7 MB 3.9 MB/s eta 0:00:16
   ---------------- ----------------------- 41.6/101.7 MB 3.8 MB/s eta 0:00:16
   ---------------- ----------------------- 41.7/101.7 MB 3.8 MB/s eta 0:00:16
   ---------------- ----------------------- 41.9/101.7 MB 3.8 MB/s eta 0:00:16
   ---------------- ----------------------- 42.0/101.7 MB 3.8 MB/s eta 0:00:16
   ---------------- ----------------------- 42.1/101.7 MB 3.7 MB/s eta 0:00:17
   ---------------- ----------------------- 42.3/101.7 MB 3.7 MB/s eta 0:00:16
   ---------------- ----------------------- 42.4/101.7 MB 3.7 MB/s eta 0:00:17
   ---------------- ----------------------- 42.5/101.7 MB 3.7 MB/s eta 0:00:17
   ---------------- ----------------------- 42.7/101.7 MB 3.6 MB/s eta 0:00:17
   ---------------- ----------------------- 42.9/101.7 MB 3.6 MB/s eta 0:00:17
   ---------------- ----------------------- 42.9/101.7 MB 3.5 MB/s eta 0:00:17
   ----------------- ---------------------- 43.2/101.7 MB 3.5 MB/s eta 0:00:17
   ----------------- ---------------------- 43.6/101.7 MB 3.5 MB/s eta 0:00:17
   ----------------- ---------------------- 43.7/101.7 MB 3.5 MB/s eta 0:00:17
   ----------------- ---------------------- 43.8/101.7 MB 3.4 MB/s eta 0:00:17
   ----------------- ---------------------- 43.9/101.7 MB 3.4 MB/s eta 0:00:18
   ----------------- ---------------------- 43.9/101.7 MB 3.4 MB/s eta 0:00:18
   ----------------- ---------------------- 44.0/101.7 MB 3.3 MB/s eta 0:00:18
   ----------------- ---------------------- 44.1/101.7 MB 3.3 MB/s eta 0:00:18
   ----------------- ---------------------- 44.1/101.7 MB 3.3 MB/s eta 0:00:18
   ----------------- ---------------------- 44.2/101.7 MB 3.2 MB/s eta 0:00:19
   ----------------- ---------------------- 44.3/101.7 MB 3.1 MB/s eta 0:00:19
   ----------------- ---------------------- 44.5/101.7 MB 3.1 MB/s eta 0:00:19
   ----------------- ---------------------- 44.6/101.7 MB 3.1 MB/s eta 0:00:19
   ----------------- ---------------------- 44.7/101.7 MB 3.1 MB/s eta 0:00:19
   ----------------- ---------------------- 44.7/101.7 MB 3.0 MB/s eta 0:00:19
   ----------------- ---------------------- 44.7/101.7 MB 3.0 MB/s eta 0:00:19
   ----------------- ---------------------- 44.8/101.7 MB 3.0 MB/s eta 0:00:20
   ----------------- ---------------------- 44.8/101.7 MB 3.0 MB/s eta 0:00:20
   ----------------- ---------------------- 44.9/101.7 MB 2.9 MB/s eta 0:00:20
   ----------------- ---------------------- 45.0/101.7 MB 2.9 MB/s eta 0:00:20
   ----------------- ---------------------- 45.0/101.7 MB 2.8 MB/s eta 0:00:20
   ----------------- ---------------------- 45.1/101.7 MB 2.8 MB/s eta 0:00:21
   ----------------- ---------------------- 45.1/101.7 MB 2.8 MB/s eta 0:00:21
   ----------------- ---------------------- 45.3/101.7 MB 2.8 MB/s eta 0:00:21
   ----------------- ---------------------- 45.4/101.7 MB 2.8 MB/s eta 0:00:21
   ----------------- ---------------------- 45.6/101.7 MB 2.7 MB/s eta 0:00:21
   ----------------- ---------------------- 45.7/101.7 MB 2.7 MB/s eta 0:00:21
   ----------------- ---------------------- 45.7/101.7 MB 2.7 MB/s eta 0:00:21
   ----------------- ---------------------- 45.7/101.7 MB 2.7 MB/s eta 0:00:22
   ------------------ --------------------- 45.8/101.7 MB 2.6 MB/s eta 0:00:22
   ------------------ --------------------- 45.9/101.7 MB 2.6 MB/s eta 0:00:22
   ------------------ --------------------- 46.1/101.7 MB 2.6 MB/s eta 0:00:22
   ------------------ --------------------- 46.4/101.7 MB 2.6 MB/s eta 0:00:21
   ------------------ --------------------- 46.6/101.7 MB 2.7 MB/s eta 0:00:21
   ------------------ --------------------- 47.0/101.7 MB 2.7 MB/s eta 0:00:21
   ------------------ --------------------- 47.1/101.7 MB 2.7 MB/s eta 0:00:21
   ------------------ --------------------- 47.4/101.7 MB 2.7 MB/s eta 0:00:21
   ------------------ --------------------- 47.7/101.7 MB 2.7 MB/s eta 0:00:21
   ------------------ --------------------- 48.1/101.7 MB 2.7 MB/s eta 0:00:20
   ------------------- -------------------- 48.5/101.7 MB 2.7 MB/s eta 0:00:20
   ------------------- -------------------- 48.8/101.7 MB 2.7 MB/s eta 0:00:20
   ------------------- -------------------- 49.0/101.7 MB 2.7 MB/s eta 0:00:20
   ------------------- -------------------- 49.0/101.7 MB 2.7 MB/s eta 0:00:20
   ------------------- -------------------- 49.6/101.7 MB 2.7 MB/s eta 0:00:20
   ------------------- -------------------- 50.1/101.7 MB 3.1 MB/s eta 0:00:17
   ------------------- -------------------- 50.4/101.7 MB 3.1 MB/s eta 0:00:17
   -------------------- ------------------- 51.0/101.7 MB 3.3 MB/s eta 0:00:16
   -------------------- ------------------- 51.4/101.7 MB 3.3 MB/s eta 0:00:16
   -------------------- ------------------- 51.7/101.7 MB 3.6 MB/s eta 0:00:14
   -------------------- ------------------- 52.1/101.7 MB 3.7 MB/s eta 0:00:14
   -------------------- ------------------- 52.3/101.7 MB 3.8 MB/s eta 0:00:14
   -------------------- ------------------- 52.5/101.7 MB 3.8 MB/s eta 0:00:14
   -------------------- ------------------- 53.0/101.7 MB 3.9 MB/s eta 0:00:13
   -------------------- ------------------- 53.4/101.7 MB 4.0 MB/s eta 0:00:12
   --------------------- ------------------ 53.8/101.7 MB 4.1 MB/s eta 0:00:12

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [43]:
from xgboost import XGBClassifier

In [44]:
xgb_model = XGBClassifier(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=6,
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)

xgb_model.fit(X_train_smote, y_train_smote)

C:\Users\jhenk\OneDrive\Desktop\Projects\Credit Card Approval Project\venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [23:32:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [45]:
xgb_pred = xgb_model.predict(X_test_scaled)

In [46]:
print("XGBoost Accuracy:", accuracy_score(y_test, xgb_pred))

print("\nXGBoost Classification Report:\n")
print(classification_report(y_test, xgb_pred))

XGBoost Accuracy: 0.8115866388308977

XGBoost Classification Report:

              precision    recall  f1-score   support

           0       0.85      0.94      0.89      1611
           1       0.31      0.15      0.20       305

    accuracy                           0.81      1916
   macro avg       0.58      0.54      0.55      1916
weighted avg       0.77      0.81      0.78      1916

In [49]:
# Three Models Comparison

models = ['Logistic Regression', 'Random Forest', 'XGBoost']
accuracy = [
    accuracy_score(y_test, y_pred),
    accuracy_score(y_test, rf_pred),
    accuracy_score(y_test, xgb_pred)
]

comparison = pd.DataFrame({
    'Model': models,
    'Accuracy': accuracy
})

comparison

                 Model  Accuracy
0  Logistic Regression  0.636743
1        Random Forest  0.811587
2              XGBoost  0.811587

In [52]:
# Downloading the files 

import joblib

joblib.dump(rf_model, "loan_prediction_model.pkl")
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']

In [53]:
import os
os.listdir()

['.ipynb_checkpoints',
 'app.py',
 'data.csv',
 'loan_default_model.pkl',
 'loan_prediction_model.ipynb',
 'loan_prediction_model.pkl',
 'models',
 'notebook',
 'requirements.txt',
 'scaler.pkl',
 'train_model.py',
 'venv']